### PR TITLE
Update to 1.20

### PR DESCRIPTION
**Pull request by TauCubed**
Hello! Once again decided to update this for me and my friends personal use and thought I'd put it here for others to compile/update from.

While all of the mods functionality seems to work, It's only had basic tests done on fabric, and forge hasn't been tested at all.

### CODE REVIEW

**Comment by mrshmllow** [comment]
:heart: Will check out soon

**Comment by CatchingPhoenix** [comment]
Hello TauCubed. I am admittedly a major novice, but I'd like to use your file and can't figure out how to get a .jar file on github for 1.20 like you say you have. Could you instruct me/point me to where I can download the mod?

**Comment by mrshmllow** [comment]
Hey @CatchingPhoenix! Welcome to GitHub!

This post is simply proposing changes, and once I accept them (soon), I will post a release where you will be able to download the mod for 1.20.

**Comment by TauCubed** [comment]
> Hello TauCubed. I am admittedly a major novice, but I'd like to use your file and can't figure out how to get a .jar file on github for 1.20 like you say you have. Could you instruct me/point me to where I can download the mod?

You would need to compile the mod yourself.
1. Download my [update-1.20](https://github.com/TauCubed/BetterRecipeBook/tree/update-1.20) branch
2. Make sure you have [JDK 17](https://adoptium.net/) or greater installed.
3. Run `./gradlew fabric:build` or `./gradlew :build` in terminal/cmd to build a jar for both fabric and forge.
4. You can find the jars in the `./(fabric or forge)/build/libs/` folder.

If you are not comfortable installing new JREs/JDKs then I would just wait for the release of the mod.

**Comment by mrshmllow** [comment]
The biggest issues remaining seem to be potion UI graphical ones. Ingredient previews are sometimes wrong and some textures are broken there too
 
 image
 
image

But besides those, the rest of the functionality is perfect on fabric from what ive seen, but forge doesnt launch for me

**Comment by TauCubed** [comment]
Interesting. I'll look into that on the weekend.

**Comment by TauCubed** [comment]
There are still things unfinished such as the new ghost logic not being applied to the crafting table (currently brewing stand only) among some other things.

**Comment by TauCubed** [comment]
I tested it on forge and fabric (as well as on a paper backend with GrimAC) and it seems to work as intended.

**Comment by mrshmllow** [comment]
They yearn for the 1.20 so I think its great for now

**Pull request merged**
