### PR TITLE
Feature force place recipe option

### PR DESCRIPTION
**Pull request by TauCubed**
Manually place ingredients in the crafting grid rather than asking the server to do it. (addresses #83)

This fixes issues where the server doesn't properly track unlocked recipes and prevents you from auto-filling recipes you haven't "unlocked" yet.
 
- [ ] ~Add Force place recipes option to New Recipes Settings~
- [X] Implement force place recipes
- [X] Support Instant Crafting
- [ ] ~Support Batch Crafting~
- [x] Automatically detect when server has locked recipe and use force place recipe.

### CODE REVIEW

**Comment by mrshmllow** [comment]
> ~~Support Batch Crafting~~

If it is truly impossible to have both unlockAll and batch crafting, maybe we can have a system to only allow batch crafting on recipes youve actually unlocked?

**Comment by TauCubed** [comment]
> > ~Support Batch Crafting~
> 
> If it is truly impossible to have both unlockAll and batch crafting, maybe we can have a system to only allow batch crafting on recipes youve actually unlocked?

It's possible to do batch crafting but it'd take a bit of work. And I'm not sure if it's needed as once you craft it it should be unlocked. Thus I'm thinking of focusing on keeping track of unlocked recipes by changing how unlock recipes works.

Or, perhaps I could implement batch crafting but idk if it's worth it.

**Review by mrshmllow — CHANGES_REQUESTED** [review]
It looks like furnaces do not work. Also, you can screw up the grid by spamming between different recipes and it can get kinda screwed up.

**Comment by TauCubed** [comment]
I completely forgot about furnace recipes existing.

**Comment by mrshmllow** [comment]
hey so i am going to repair the git history of this branch its kinda wrecked

**Comment by mrshmllow** [comment]
Okay that was scary but it should have no conflicts now

**Comment by mrshmllow** [comment]
Ideally, this code becomes a "force unlock" and will only need to be used a single time per recipe. When you instant craft the first craft will be forced and then it falls back on the server to do the rest. The shift-click problem goes away if we simply place a single set and then re-send the request to shift click like nothing happened.

**Comment by TauCubed** [comment]
Yep that is currently how it behaves.

**Comment by mrshmllow** [comment]
It is still possible to break the recipe but since [9ae3d6f](https://github.com/mrshmllow/BetterRecipeBook/pull/86/commits/9ae3d6f7590aed74770f43f53888ef7a8cf6a1bb) its a lot more stable

**Comment by TauCubed** [comment]
I didn't want to do it that way because it can generate way too many inventory click packets. 

For instance, crafting 64 gold ingots from gold nuggets will require one click to pickup stack, one click to place a single item and one more click to place the stack back. This means it will create (64 x 9 * 2.98)=1716 inventory click packets. Any server distro with reasonable packet rate limits (such as paper) will cause you to get kicked or for some of the packets to get dropped and end up making a right mess.

While it would be possible to avoid placing the stack back and thus reduce the amount to around 1100, it's still way too many and I don't think this is a good idea.

**Comment by mrshmllow** [comment]
Sorry, I hadn't thought that through. I think if it is too hard to support it, there must be a better user experience than stuff not working as a user might expect and getting in their way.

I think it would be nicer to turn this whole thing from unlock all to "display locked" and have some kind of info on screen. Ill think about it more.

**Comment by mrshmllow** [comment]
Batch crafting isn't required I just want a better way to display the difference for a better user experience

**Comment by mrshmllow** [comment]
Something like this is what i had in mind

image

**Review by mrshmllow — APPROVED** [review]

**Pull request merged**
