### PR TITLE
Update 1.19.3

### PR DESCRIPTION
**Pull request by TauCubed**
Haven't had time to extensively test but seems to work properly.

For #57

### CODE REVIEW

**Comment by mrshmllow** [comment]
my goodness.

**Comment by mrshmllow** [comment]
this takes far more knowledge of minecraft's codebase than i have

**Comment by TauCubed** [comment]
The main changes are that 1.19.3 removed the Widget interface in favor of the AbstractWidget class.
They also split the registry into Registry and BuiltInRegistries.

Truth be told I didn't take the time to deep drive into the diffs and re-implement functionality against the source code, I just updated it so it worked as required and my friend could enjoy it.

Besides, this is just a minor update so it's not like the legacy code would remove new functionality from the recipe book or anything.

**Comment by mrshmllow** [comment]
Everything seems to be working

**Comment by TauCubed** [comment]
Had the same issue running the forge test. Assumed it was the configs.
Compiled it both for fabric and forge and tested it on both, seemed to work fine on both.

**Comment by mrshmllow** [comment]
Forge seems to work fine!

**Pull request merged**
