### PR TITLE
road to compat

### PR DESCRIPTION
**Pull request by mrshmllow**
the goal of this pull request is to take the first steps to reduce code duplication between vanilla & smithing & brewing and eventually get to a stage where we can support future screens effectively (without onboarding 2000 lines and 8 classes) and/or other mods [like this](https://modrinth.com/mod/recipe-book-delight)

### CODE REVIEW

**Comment by mrshmllow** [comment]
so pretty...

image

**Comment by mrshmllow** [comment]
@TauCubed Id like your thoughts on the direction this PR is going. I wanna get it to a point where new recipe books only need to implement getting list of recipes, ghosting them, and placing them

**Comment by TauCubed** [comment]
I think that's a great idea.
The less vanilla code we use the easier it will be to maintain.

**Comment by mrshmllow** [comment]
I dont think its possible to raw extend RecipeBookComponent (etc) because java so GenericRecipeBookComponent and reimplementing it is as close as ive managed to get

**Comment by mrshmllow** [comment]
250 lines removed

**Comment by mrshmllow** [comment]
Its pretty much done

**Pull request merged**
