### PR TITLE
1.10.0+1.20.0-1

### PR DESCRIPTION
**Pull request by mrshmllow**

### CODE REVIEW

**Review by TauCubed — CHANGES_REQUESTED** [review]
issue with overlay
image

**Comment by TauCubed** [comment]
Not sure if this is a 1.20 issue or if this is in the main branch but I'm having issues pinning/unpinning recipes when the recipe page isn't focused.

Pins are also not rendered on the overlay page of the smithing book.
image

**Comment by TauCubed** [comment]
Another issue: Instant crafting a recipe causes a / by zero.

https://pastebin.com/934tJ6Mu

**Comment by mrshmllow** [comment]
> Not sure if this is a 1.20 issue or if this is in the main branch but I'm having issues pinning/unpinning recipes when the recipe page isn't focused on both the smithing table and the brewing stand.

main branch thing.. will fix eventually

> Pins are also not rendered on the overlay page of the smithing book.

Oh no.. i might of forgotten that was even a thing lmao

**Comment by mrshmllow** [comment]
> It also seems that the pin texture is overwritten by the neighboring draw.

If you mean the pin is underneath the fake item, i cant figure it out the render stack is too confusing for me 🫠

**Pull request merged**
