### PR TITLE
[1.10.0] Smithing Table Recipe Book

### LINKED ISSUE #37: [Request] Smithing Table Recipe Book
Regarding Vanilla, a Smithing Table recipe book would be really good, specially for packs trying to not rely on JEI/REI. Support for the more famous modded workstations with a GUI would be good too, such as the Cooking Pot from Farmer's Delight.

### PR DESCRIPTION
**Pull request by mrshmllow**
Closes #37 

- [x] Cycle armour over time 
- [x] Group by armour type
- [x] Centered interface support
- [x] Pinning support
- [ ] ~~Instant Craft~~
- [x] Ghost recipes
- [x] Ghost result
- [x] Armour stand preview
- [x] Remove unnecessary AW's 
- [x] Fix clicking trim recipe twice crafts
- [x] fix overlays when non cantered screen

### CODE REVIEW

**Comment by mrshmllow** [comment]
Progress so far

image

**Comment by mrshmllow** [comment]
Item transformations are completely functional

image

**Comment by mrshmllow** [comment]
Technically instant craft can be implemented in this screen as well

**Comment by TauCubed** [comment]
I'll do some testing this weekend.
One thing I might change is the ghost recipe. From a maintainability standpoint it might be better to make BrewingGhostRecipe the general purpose ghost recipe including all the features needed. That's why I originally named it MyGhostRecipe and not just to do with Brewing.

IIRC BrewingGhostRecipe doesn't do anything potion specific. It just gives you more functions/features to use.

**Comment by mrshmllow** [comment]
Yeah your right about ghost recipes

I just wanna completely rewrite the whole mod in kotlin every time I update it lol

**Comment by TauCubed** [comment]
I'd recommend merging the code from SmithingGhostRecipe to BrewingGhostRecipe and naming it back to MyGhostRecipe as hovering over the ghost recipe renders the tooltip even if the slot is filled. Causing two tooltips to be rendered. MyGhostRecipe has a rendering predicate for this purpose. This can be caused by clicking on a recipe you can't craft and then clicking on one you can.

I've noticed a few other bugs:
The ghost recipe doesn't disappear when clicked, it instead blocks items from being placed.

It also seems to randomly craft items when I spam between the options.

**Comment by mrshmllow** [comment]
> I'd recommend merging the code from SmithingGhostRecipe to BrewingGhostRecipe and naming it back to MyGhostRecipe as hovering over the ghost recipe renders the tooltip even if the slot is filled. Causing two tooltips to be rendered. MyGhostRecipe has a rendering predicate for this purpose. This can be caused by clicking on a recipe you can't craft and then clicking on one you can.

image

vanilla bug

**Comment by mrshmllow** [comment]
I think for right now vanilla & the mod has bugs with ghosts and id like to fix them all but probably at a later date

**Pull request merged**
