### PR TITLE
1.20.2 Update

### PR DESCRIPTION
**Pull request by TauCubed**
Update and various changes and fixes in this PR.

- Keep hovered recipe button displayed if removing it could lead to accidental crafting when instant crafting.
- Fix pins in alternative recipes menu
- Refactoring
- Updated to 1.20.2
- Improve scrolling
- Give settings button a gear icon
- Reduce jar filesize by not including .ase and kra files.
- Removed dark mode as texturing should and can be done easily with the new sprites system.

### CODE REVIEW

**Comment by TauCubed** [comment]
For those who can't built the project themselves but want to be able to use it: https://mega.nz/file/xoVH3CDb#TIxqIJyPytc9XsDVOXdnw82KDa0N0XABi3uzuCi72Ls

**Comment by mrshmllow** [comment]
Thanks! I will review all of this soon.

**Comment by mrshmllow** [comment]
Sorry! Ive been extremely busy recently with school and exams and whatnot

**Comment by mrshmllow** [comment]
All of this seems to be running great!

**Review by mrshmllow — APPROVED** [review]

**Comment by mrshmllow** [comment]
@TauCubed do you have a discord or twitter or something I could add you on?

**Comment by TauCubed** [comment]
Yes. `@taucu` on discord.

**Pull request merged**
