### PR TITLE
Update for 1.19.4

### PR DESCRIPTION
**Pull request by MehradN**
This seems to be working.

### Changes:
- `renderButton` got renamed to to `renderWidget`.
- `setFocus` got renamed to `setFocused`.
- Some methods now receive a `PoseStack` as first argument.
- Some methods now receive a `RegistryAccess` as first argument. Please double check these changes, I tried my best to pass the correct `RegistryAccess`, but I might have messed up.
- In `RecipeBookWidget`, I could either create an empty `renderWidget` method and continue to override `render` method, or I could override the `renderWidget` method instead. And I did the latter. Please double check this as well.

Also the currently used versions of ModMenu and Forge seem to be in beta phase. Maybe we should wait for them to release the final version.

### CODE REVIEW

**Comment by mrshmllow** [comment]
cooool

**Comment by TauCubed** [comment]
Damn, I didn't check the PRs and updated it as well haha.
One minor change I'd make (idk if it's worth a PR of its own) is to fix an issue where the settings screen is opened twice from the menu.

This is down to the order of some instructions being wrong in the SettingsButton

```java
if (this.settingsButton != null && BetterRecipeBook.config.settingsButton && this.isVisible()) {
    if (this.settingsButton.mouseClicked(mouseX, mouseY, button)) {
        cir.setReturnValue(true);
    }
}
```

The above code appears to resolve the issue in my branch.

**Comment by mrshmllow** [comment]
I was waiting for libraries and stable releases as well

**Comment by mrshmllow** [comment]
1.20 might also bring some feature releases of this mod as well, we will see how it goes

**Comment by MehradN** [comment]
@TauCubed Do you want me to add that to this pull request?

**Comment by MehradN** [comment]
@mrshmllow Why is ModMenu a dependency for the fabric version?
It is possible to add support for ModMenu without having it as a runtime dependency.

**Comment by TauCubed** [comment]
Yes. As I said, I don't think it'd be worth a PR of it's own.

**Comment by mrshmllow** [comment]
this pr looks fine i think

**Pull request merged**
